###############################################################
#
#
# Makefile for BatFaker
###############################################################

# Executables to be built (must have matching .cxx files)
BINS := MapRawFile BatFaker

# Library to be built
LIBNAME := BatFaker

# Set up CDMS build system
include ../makefiles/cdmsbats.mk

