###############################################################
# $Id$
#
# Makefile for BatRoot
###############################################################

# Executables to be built (must have matching .cxx files)
BINS := PulseSimBuilder

# Library to be built
LIBNAME := PulseSimBuilder

# Set up CDMS build system
include ../makefiles/cdmsbats.mk

