#!/bin/bash
#
# Arguments:
# $1 : series number
# $2 : dump number
# $3 : max events to process
# $4 : datatype (ba, bg or cf)
# $5 : run (i.e. R123, R124,...)
#

date

###### Configuration Setup #######
. /usr/local/etc/setups.sh
. /local/ups/grid/setup.sh
echo Hostname: `hostname`
export HOSTNAME=`hostname`

##### Construct dump name from dump num #####
DUMPID=$2;
NLEADZEROS=4;
let NLEADZEROS-=${#DUMPID};

while [ "$NLEADZEROS" -ge "1" ]
    do DUMPID=0$DUMPID;
    let NLEADZEROS-=1;
done

DUMPID=F$DUMPID;

##### Check to see if nsf disk is available #####
while [ ! -e /grid/data/cdms/processing ]
  do cd /grid/data/cdms/processing; sleep 1;
done

##### Using autogenerated condor directory #####
cd $_CONDOR_SCRATCH_DIR
/bin/mkdir -p $_CONDOR_SCRATCH_DIR/br_input/
/bin/mkdir -p $_CONDOR_SCRATCH_DIR/br_output/
/bin/cp /grid/data/cdms/processing/raw/$5/$4/$1/$1_$DUMPID.gz $_CONDOR_SCRATCH_DIR/br_input/.

######### Run br #################

export ROOTSYS=/grid/fermiapp/cdms/processing_source/root_v5.22
echo $ROOTSYS
export PATH=$ROOTSYS/bin:$PATH
export LD_LIBRARY_PATH=$ROOTSYS/lib:$LD_LIBRARY_PATH

export BATROOTDIR=/grid/fermiapp/cdms/processing_source/cdmsbats/BatRoot
echo $BATROOTDIR
export BATROOT_RAWDATA=$_CONDOR_SCRATCH_DIR/br_input
echo $BATROOT_RAWDATA
export BATROOT_AUXFILES=/grid/data/cdms/processing/raw/$5/$4/$1
echo $BATROOT_AUXFILES
export BATROOT_NOISEFILES=/grid/data/cdms/processing/noise_files/$5/ROOT
echo $BATROOT_NOISEFILES
export BATROOT_RQDATA=$_CONDOR_SCRATCH_DIR/br_output
echo $BATROOT_RQDATA
export BATROOT_GPIBFILES=/grid/data/cdms/processing/raw/gpib
echo $BATROOT_GPIBFILES

$BATROOTDIR/BatRoot $1 $2 $3 processingSoudanData.$5Grid.$4 >& $_CONDOR_SCRATCH_DIR/br_output/$1_$DUMPID.brlog

##################################

#for checking scripts
ls -l $_CONDOR_SCRATCH_DIR/br_input/
ls -l $_CONDOR_SCRATCH_DIR/br_output/

#move the output file back to storage
mkdir -p -m 775 /grid/data/cdms/processing/br_output/$5/$4/$1
/bin/cp -f $_CONDOR_SCRATCH_DIR/br_output/*_$1_$DUMPID.root /grid/data/cdms/processing/br_output/$5/$4/$1/.

#move log file back to storage
mkdir -p -m 775 /grid/data/cdms/processing/br_logs/$1/
/bin/cp -f $_CONDOR_SCRATCH_DIR/br_output/$1_$DUMPID.brlog /grid/data/cdms/processing/br_logs/$1/.

#cleanup - no needed to with $_CONDOR_SCRATCH_DIR, but just in case
/bin/rm -f $_CONDOR_SCRATCH_DIR/br_input/$1_$DUMPID.gz
/bin/rm -f $_CONDOR_SCRATCH_DIR/br_output/*_$1_$DUMPID.root
/bin/rm -f $_CONDOR_SCRATCH_DIR/br_output/$1_$DUMPID.brlog

date




