###############################################################
#
#
# Makefile for BatViewer
###############################################################

# Executables to be built (must have matching .cxx files)
BINS := BatViewer

# Library to be built
LIBNAME := BatViewer

# Set up CDMS build system
include ../makefiles/cdmsbats.mk

